### ISSUE TITLE
[dglo on 2011-08-25 19:25:04] : pDAQ: splicer - avoid potential NPE

### ISSUE THREAD

**Issue by dglo** [dglo/splicer#46]
While running the daq-integration-test unit tests, I've occasionallt hit this exception:

Exception in thread "QueueThread-eventBuilder*RdoutData#118" java.lang.NullPointerException
        at icecube.daq.splicer.HKN1Comparator.compare(HKN1Splicer.java:625)
        at icecube.daq.splicer.HKN1Comparator.compare(HKN1Splicer.java:610)
        at icecube.daq.hkn1.Node.compare(Node.java:53)
        at icecube.daq.hkn1.Node.checkList(Node.java:85)

**Comment by dglo** [comment]
[dglo on 2011-08-25 19:29:17]
svn commit -m"Issue 5131: Avoid null objects when comparing spliceables" splicer/src/main/java/icecube/daq/splicer/HKN1Splicer.java
Sending        splicer/src/main/java/icecube/daq/splicer/HKN1Splicer.java
Transmitting file data .
Committed revision 13291.

**Comment by dglo** [comment]
[dglo on 2012-05-10 15:05:18]
These issues are all in releases
